---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: acme-fitness
spec:
  serviceAccountName: acme-fitness-sa
  packageRef:
    refName: acme-fitness-sa.external.demo-dependencies.learn
    versionSelection:
      constraints: 1.0.0
  values:
  - secretRef:
      name: acme-fitness-values
---
apiVersion: v1
kind: Secret
metadata:
  name: acme-fitness-values
stringData:
  values.yml: |
    ---
    namespace: app-acme-fitness