#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata": {"namespace": "default"}}), expects=8
---
metadata:
  namespace: #@ data.values.namespace