apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: acme-fitness.external.demo-dependencies.learn.1.0.0
spec:
  refName: acme-fitness.external.demo-dependencies.learn
  version: 1.0.0
  releaseNotes: |
    Initial release of the acme-fitness package
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          description: Namespace to deploy
          default: acme-fitness
        fqdn:
          type: string
          description: FQDN
          default: ""
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/doddatpivotal/acme-fitness-package-repo
          ref: origin/main
          subPath: packages/acme-fitness/1.0.0/bundle
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
